# Generated by Django 4.1.7 on 2023-03-14 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('id_no', models.IntegerField()),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('is_remote', models.BooleanField(choices=[('At Site', 'At Site'), ('Remote', 'Remote')], default='At Site', verbose_name='دورکاری')),
                ('time_start', models.TimeField(default=django.utils.timezone.now, verbose_name='زمان شروع')),
                ('time_end', models.TimeField(default=django.utils.timezone.now, verbose_name='زمان پایان')),
                ('description', models.TextField(max_length=100, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Core.employee')),
            ],
        ),
    ]
